# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionsource', '0004_auto_20170510_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecters',
            name='id_source_RS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='collecters',
            name='timer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='collectesite',
            name='id_source_site',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='collectesite',
            name='timer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sourcers',
            name='id_operateur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sourcesite',
            name='id_operateur',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
